---
- hosts: mywebserves
  become: yes
  tasks:
  - name: i want execute linux command
    command: hostname -f 
    register: myfristvaribleresults 

  - name: i want to display first task results
    debug: 
      msg: "{{myfristvaribleresults}}"

  - name: install git
    apt: 
     name: git 
     state: present 
    when: myfristvaribleresults.stderr ==""

  - name: install tree
    yum: 
      name: tree
      state: present
    when: myfristvaribleresults.stderr !=""     
