---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want install webserver on ubuntu server
    apt:
     name: "{{mywebserverpackonubuntu}}"
     state: present
    when: ansible_os_family== "Debian"

  - name: i want start webserver on ubuntu server
    service: 
      name: apache2
      state: started
    when: ansible_os_family== "Debian"

  - name: install mywebserver on RedHat ansible nodes
    yum:
      name: "{{mywebserverpackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: start webserver on RedHat ansible nodes
    service: 
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"