---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:
  - name: install mywebserver on ubuntu ansible nodes
    apt:
     name: "{{[mywebserverpackonubuntu]}}"
     state: present
    when: ansible_os_family== "Debian"

  - name: start webserver on ubuntu ansible nodes
    service: 
      name: apache2
      state: started
    when: ansible_os_family== "Debian"

  - name: install mywebserver on RedHat ansible nodes
    yum:
      name: "{{mywebserverpackonredhat}}"
      state: present
    when: ansible_os_family== "RedHat"

  - name: start webserver on RedHat ansible nodes
    service: 
      name: httpd
      state: started
    when: ansible_os_family== "RedHat"